name: Build and Push Images

on:
  workflow_call:
    inputs:
      projects:
        required: true
        type: string
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ${{ fromJson(inputs.projects) }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
       
      - name: Create Maven Settings File
        run: |
          echo "${{ secrets.GH_MAVEN_SETTINGS }}" | base64 --decode > 1on1bet-be/settings.xml
          ls -l 1on1bet-be 
          cat 1on1bet-be/settings.xml 

      - name: Create and push new tag
        run: |
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
          VERSION_PARTS=(${TAG//./ })
          PATCH_VERSION=${VERSION_PARTS[2]}
          NEW_PATCH_VERSION=$((PATCH_VERSION + 1))
          NEW_TAG="v${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.$NEW_PATCH_VERSION"
          
          # Set up Git authentication using the token
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://github-actions:${{ secrets.GH_TAG_TOKEN }}@github.com/GeeksInnovation/gi-1on1bet.git

          git fetch --tags
          git tag $NEW_TAG
          git push origin --tags

          echo "NEW_TAG=${NEW_TAG}" >> $GITHUB_ENV


      - name: Build Docker Image
        run: |
          docker build --build-arg MAVEN_CONFIG=settings.xml \
            -t ghcr.io/geeksinnovation/gi-1on1bet/${{ matrix.project }}:${{ env.NEW_TAG }} \
            -f 1on1bet-be/${{ matrix.project }}/Dockerfile 1on1bet-be/

      - name: Push Docker Image
        run: |
          echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u ${{ github.actor }}  --password-stdin
          docker push ghcr.io/geeksinnovation/gi-1on1bet/${{ matrix.project }}:${{ env.NEW_TAG }}
