name: Build and Push Images

on:
  workflow_call:
    inputs:
      projects:
        required: true
        type: string
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ${{ fromJson(inputs.projects) }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          cd 1on1bet-be/${{ matrix.project }}
          docker build -t ghcr.io/your-org/${{ matrix.project }}:latest .

      - name: Push Docker Image
        run: |
          echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u your-username --password-stdin
          docker push ghcr.io/your-org/${{ matrix.project }}:latest
