name: Build and Push Images

on:
  workflow_call:
    inputs:
      projects:
        required: true
        type: string
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ${{ fromJson(inputs.projects) }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Create Maven Settings File
        run: |
          mkdir -p ~/.m2
          echo "${{ secrets.GH_MAVEN_SETTINGS }}" | base64 --decode > ~/.m2/settings.xml
          cp ~/.m2/settings.xml 1on1bet-be/settings.xml
          ls -l 1on1bet-be 

      - name: Build Docker Image
        run: |
          docker build --build-arg MAVEN_CONFIG=/root/.m2/settings.xml \
            -t ghcr.io/your-org/${{ matrix.project }}:latest \
            -f 1on1bet-be/${{ matrix.project }}/Dockerfile 1on1bet-be/

      - name: Push Docker Image
        run: |
          echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u your-username --password-stdin
          docker push ghcr.io/your-org/${{ matrix.project }}:latest
