name: Build and Push Images

on:
  workflow_call:
    inputs:
      projects:
        required: true
        type: string
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ${{ fromJson(inputs.projects) }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
       
      - name: Create Maven Settings File
        run: |
          echo "${{ secrets.GH_MAVEN_SETTINGS }}" | base64 --decode > 1on1bet-be/settings.xml
          ls -l 1on1bet-be 
          cat 1on1bet-be/settings.xml 

      - name: Get Commit SHA
        run: |
          COMMIT_SHA=$(git rev-parse HEAD)
          echo "COMMIT_SHA=${COMMIT_SHA}" >> $GITHUB_ENV


      - name: Build Docker Image
        run: |
          docker build --build-arg MAVEN_CONFIG=settings.xml \
            --build-arg MAVEN_OPTS="-Dcheckstyle.skip=true" \
            -t ghcr.io/geeksinnovation/gi-1on1bet/${{ matrix.project }}:${{ env.COMMIT_SHA }} \
            -f 1on1bet-be/${{ matrix.project }}/Dockerfile 1on1bet-be/

      - name: Push Docker Image
        run: |
          echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u ${{ github.actor }}  --password-stdin
          docker push ghcr.io/geeksinnovation/gi-1on1bet/${{ matrix.project }}:${{ env.COMMIT_SHA }}
