name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feat/**
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/feat/')
    uses: ./.github/workflows/run-tests.yml  

  detect-changes:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/detect-changes.yml  

  # build-and-push:
  #   if: github.ref == 'refs/heads/main'
  #   needs: detect-changes
  #   uses: ./.github/workflows/build-and-push.yml  
  #   with:
  #     projects: ${{ needs.detect-changes.outputs.projects }}