name: Run Tests

on:
  push:
    branches:
      - main
      - feat/**

  pull_request:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Maven Authentication & Repositories
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ secrets.GH_USERNAME }}</username>
                <password>${{ secrets.GH_PAT }}</password>
              </server>
            </servers>
            <mirrors>
              <mirror>
                <id>central</id>
                <mirrorOf>central</mirrorOf>
                <url>https://repo1.maven.org/maven2</url>
              </mirror>
            </mirrors>
            <profiles>
              <profile>
                <id>github</id>
                <repositories>
                  <repository>
                    <id>github</id>
                    <url>https://maven.pkg.github.com/geeksinnovation/gi-1on1bet-utils</url>
                    <snapshots>
                      <enabled>true</enabled>
                    </snapshots>
                  </repository>
                </repositories>
              </profile>
            </profiles>
            <activeProfiles>
              <activeProfile>github</activeProfile>
            </activeProfiles>
          </settings>
          EOF

      - name: Set Backend Directory
        run: |
          cd 1on1bet-be
          echo "Current Directory: $(pwd)"

      - name: Run Tests for All Projects
        run: |
          cd 1on1bet-be
          for project in */; do
            if [ -d "$project" ]; then
              echo "Running tests for $project..."
              cd "$project"
              mvn clean test
              cd ..
            fi
          done