name: Run Tests

on:
  workflow_call:
    inputs:
      project:
        required: false
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Tests for All Projects
        run: mvn clean test
